name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '58 1 * * *'
  push:
    paths:
      - '**.lua'
      - '**.txt'
env:
  GH_TOKEN: ${{ github.token }}
  msg: ${{ github.event.head_commit.message }}
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
      - name: Lua main
        if: ${{ !contains(env.msg, 'test.lua') }}
        run: lua .github/main.lua '${{ github.event_name }}'
      - name: Lua test
        if: ${{ contains(env.msg, 'test.lua') }}
        run: lua .github/test.lua '${{ env.msg }}'
